export const SITENAME = '睡 <rust> portfolio';
export const SITEDESCRIPTION = 'Generated by Next.js';
export const SITEURL = 'https://signalrs.com';
export const SITELOGO = '/logo.png';

export const PUBLISHER = '睡 as SUI';
export const EMAIL = 'sui.ring.endless@gmail.com';
export const GITHUB = 'https://github.com/sui-ring';
export const LIVE = 'Japan';
export const ADDRESS = 'Tokyo, Japan';
